routes/web.php
<?php

Route::namespace('Admin')->middleware('auth')->group(function(){
    Route::get('admin/home',function(){
        return view('admin.home');
    })->name('admin.home');
    // pelayan ibadah
    route::get('jadwal-pelayanan-pagi','jadwalPelayananController@pagi')->name('jPelayanan.pagi');
    route::get('jadwal-pelayanan-siang','jadwalPelayananController@siang')->name('jPelayanan.siang');
    route::get('jadwal-pelayanan-sore','jadwalPelayananController@sore')->name('jPelayanan.sore');
    route::patch('jadwal-pelayanan-pagi/{id}','jadwalPelayananController@updatePagi')->name('jPelayananPagi.update');
    route::patch('jadwal-pelayanan-siang/{id}','jadwalPelayananController@updateSiang')->name('jPelayananSiang.update');
    route::patch('jadwal-pelayanan-sore/{id}','jadwalPelayananController@updateSore')->name('jPelayananSore.update');
    // galeri
    route::resource('galeri','galeriController');
    // route::resource('pagi','ibadahPagiController');
    route::resource('pelayan','PelayanController');
    route::resource('pelayanan','pelayananController');

    // pembacaan firman minggu lalu
    Route::resource('pembacaan-firman','firmanMingguController');

    // Jadwal Ibadah
    Route::resource('admin-jadwal-ibadah','jadwalIbadahController');
});

Route::namespace('User')->group(function () {
    Route::get('/','navigationController@beranda')->name('user.beranda');
    Route::get('/tentang-gereja','navigationController@tentangGereja')->name('user.tentangGereja');
    Route::get('/jadwal-ibadah','navigationController@jadwalIbadah')->name('user.jadwalIbadah');
    Route::get('/jadwal-pelayanan','navigationController@jadwalPelayanan')->name('user.jadwalPelayanan');
    Route::get('/Galeri','navigationController@galeri')->name('user.galeri');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    @include('admin.layouts.head')
  </head>

  <body id="page-top">

    @include('admin.layouts.navbar')

    <div id="wrapper">

      <!-- Sidebar -->
      @include('admin.layouts.sidebar')

      @section('content')
        @show

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    @section('modal')
    @show

    @include('admin.layouts.footer')
    
  </body>

</html>

resources/views/admin/layouts/footer.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{asset('admin/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<!-- Core plugin JavaScript-->
<script src="{{asset('admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>

<!-- Page level plugin JavaScript-->
<script src="{{asset('admin/vendor/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('admin/vendor/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/vendor/datatables/dataTables.bootstrap4.js')}}"></script>

<!-- Custom scripts for all pages-->
<script src="{{asset('admin/js/sb-admin.min.js')}}"></script>

<!-- Demo scripts for this page-->
<script src="{{asset('admin/js/demo/datatables-demo.js')}}"></script>
<script src="{{asset('admin/js/demo/chart-area-demo.js')}}"></script>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Dashboard</title>

    <!-- Bootstrap core CSS-->
    <link href="{{asset('admin/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{{asset('admin/vendor/fontawesome-free/css/all.min.css" rel="styleshee')}}t" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{{asset('admin/vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{asset('admin/css/sb-admin.css')}}" rel="stylesheet">

    {{-- font awesome --}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    @section('styleSection')
    @show

resources/views/admin/layouts/navbar.blade.php
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{{route('home')}}">Admin</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ route('logout') }}"
              onclick=" event.preventDefault();
                        document.getElementById('logout-form').submit();">
              {{ __('Logout') }}
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </div>
      </li>
    </ul>

  </nav>

resources/views/admin/layouts/sidebar.blade.php
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{{route('admin.home')}}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span>
      </a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-fw fa-folder"></i>
        <span>Jadwal Pelayanan</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <h6 class="dropdown-header">Waktu</h6>
        <a class="dropdown-item" href="{{route('jPelayanan.pagi')}}">Ibadah Pagi</a>
        <a class="dropdown-item" href="{{route('jPelayanan.siang')}}">Ibadah Siang</a>
        <a class="dropdown-item" href="{{route('jPelayanan.sore')}}">Ibadah Sore</a>
      </div>
      <li class="nav-item">
        <a class="nav-link" href="{{route('admin-jadwal-ibadah.index')}}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Jadwal Ibadah</span></a>
      </li>
      {{-- <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <h6 class="dropdown-header">Login Screens:</h6>
        <a class="dropdown-item" href="login.html">Login</a>
        <a class="dropdown-item" href="register.html">Register</a>
        <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
        <div class="dropdown-divider"></div>
        <h6 class="dropdown-header">Other Pages:</h6>
        <a class="dropdown-item" href="404.html">404 Page</a>
        <a class="dropdown-item" href="blank.html">Blank Page</a>
      </div> --}}
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{route('pelayan.index')}}">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Daftar Pelayan</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{route('pembacaan-firman.show',1)}}">
          <i class="fas fa-fw fa-table"></i>
          <span>Pembacaan Firman</span></a>
        </li>
    <li class="nav-item">
      <a class="nav-link" href="{{route('galeri.index')}}">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Galeri</span></a>
    </li>
  </ul>