routes/web.php
<?php

Route::namespace('Admin')->middleware('auth')->group(function(){
    Route::get('admin/home',function(){
        return view('admin.home');
    })->name('admin.home');
    // pelayan ibadah
    route::get('jadwal-pelayanan-pagi','jadwalPelayananController@pagi')->name('jPelayanan.pagi');
    route::get('jadwal-pelayanan-siang','jadwalPelayananController@siang')->name('jPelayanan.siang');
    route::get('jadwal-pelayanan-sore','jadwalPelayananController@sore')->name('jPelayanan.sore');
    route::patch('jadwal-pelayanan-pagi/{id}','jadwalPelayananController@updatePagi')->name('jPelayananPagi.update');
    route::patch('jadwal-pelayanan-siang/{id}','jadwalPelayananController@updateSiang')->name('jPelayananSiang.update');
    route::patch('jadwal-pelayanan-sore/{id}','jadwalPelayananController@updateSore')->name('jPelayananSore.update');
    // galeri
    route::resource('galeri','galeriController');
    // route::resource('pagi','ibadahPagiController');
    route::resource('pelayan','PelayanController');
    route::resource('pelayanan','pelayananController');

    // pembacaan firman minggu lalu
    Route::resource('pembacaan-firman','firmanMingguController');

    // Jadwal Ibadah
    Route::resource('admin-jadwal-ibadah','jadwalIbadahController');
});

Route::namespace('User')->group(function () {
    Route::get('/','navigationController@beranda')->name('user.beranda');
    Route::get('/tentang-gereja','navigationController@tentangGereja')->name('user.tentangGereja');
    Route::get('/jadwal-ibadah','navigationController@jadwalIbadah')->name('user.jadwalIbadah');
    Route::get('/jadwal-pelayanan','navigationController@jadwalPelayanan')->name('user.jadwalPelayanan');
    Route::get('/Galeri','navigationController@galeri')->name('user.galeri');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/firman/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div id="content-wrapper">

    <div class="container-fluid">
<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-table"></i>
     Pembacaan Firman
    {{-- <span><a href="{{route('pelayan.create')}}" class="btn btn-success float-right">Tambah</a></span> --}}
    </div>
    <div class="card-body">
        <form action="{{route('pembacaan-firman.update',$data->id)}}" method="POST">
            @csrf @method('PATCH')
            <div class="form-group">
              <label for="formGroupExampleInput">Judul Khotbah</label>
              <input name="judul" type="text" class="form-control" id="formGroupExampleInput" placeholder="Masukan Data" value="{{$data->judul}}">
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Pembawa Firman</label>
              <input name="pengkhotbah" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Data" value="{{$data->pengkhotbah}}">
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Ayat Pokok</label>
              <input name="ayat" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Data" value="{{$data->ayat}}">
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Isi Firman</label>
              <textarea name="isi" class="form-control" id="exampleFormControlTextarea1" rows="3">{{$data->isi}}</textarea>
            </div>
            <button onclick="alert('berhasil diubah!')" type="submit" class="btn-ubah btn btn-success">Ubah</button>
          </form>
    </div>
    @if($data->updated_at!=null)
            <div class="card-footer small text-muted">{{$data->updated_at->diffForHumans()}}</div>
            @endif
  </div>
    </div>
</div>
@endsection